<?php
session_start();

if (!isset($_SESSION['username'])) {
    echo "<script type='text/javascript'> alert('Please log in first!') </script>";
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
}
if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['username']);
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Request</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

<body>

<div>
    Welcome <?php echo $_SESSION['username']?> !
</div>

<br>

<div id="first">
    <p id="requestInfo"></p>

    <form action="finishOneRequest.php">
        <input type="submit" value="Finish" id="finish"/>
    </form>

    <form action="suspendOneRequest.php">
        <input type="submit" value="Later" id="later"/>
    </form>

    <p id="requestSize"></p>

    <table style="width: 100%;">
        <caption style="font-weight: bold; font-size: large;">Request History</caption>
        <tr>
            <th>State</th>
            <th>Generated By</th>
            <th>Created Time</th>
            <th>Finished Time</th>
        </tr>
        <?php
        error_reporting(E_ALL);
        ini_set('display_errors', 1);

        include("credentials.php");

        try {
            $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

            $pdo = new PDO($dsn,$db_username,$db_password);

            $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

            $stmt = $pdo->prepare("SELECT * FROM Requests WHERE Handled_By = :handled_by;");

            $stmt->bindParam(':handled_by', $_SESSION['username']);

            $stmt->execute();

            $rows = $stmt->fetchAll();

            foreach ($rows as $row) {
                echo "<tr><td>" . $row['State'] . "</td><td>" .$row['Generated_By'] . "</td><td>" . $row['Created_Time'] . "</td><td>" . $row['Finished_Time'] . "</td></tr>";
            }

        } catch (Exception $exception){
            echo "<script type='text/javascript'> alert('Error for search history query!') </script>";
            exit(0);
        }
        ?>
    </table>

    <p>
        <a href="admin.php?logout='1'">logout</a>
    </p>
</div>

<script>

    function initial() {
        $.get("nextRequest.php", function (email) {
            if (email === "null"){
                document.getElementById('requestInfo').innerHTML = "There is no waiting request with no assistant handling in the queue now.";
                document.getElementById('finish').disabled = true;
                document.getElementById('later').disabled = true;
            } else {
                document.getElementById('requestInfo').innerHTML = "You should be coming for " + email + ".";
                document.getElementById('finish').disabled = false;
                document.getElementById('later').disabled = false;
            }
        });

        $.get("requestSize.php", function (size) {
            document.getElementById('requestSize').innerHTML = 'Waiting requests size (includes being handling ones): ' + size;
        });
    }

    initial();

    setInterval(initial, 1000)


</script>

</body>

</html>

