<?php
session_start();

include('credentials.php');

$success = 0;

if (!isset($_SESSION['username'])) {
    echo "<script type='text/javascript'> alert('Please log in first!') </script>";
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
    exit(0);
}
if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['username']);
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
    exit(0);
}


try {

    $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

    $pdo = new PDO($dsn,$db_username,$db_password);

    $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

    $rows = $pdo->query("SELECT * FROM Admins;");

    foreach ($rows as $row) {
        if ($row['Email'] == $_SESSION['username']) {
            $success = 1;
        }
    }

    if ($success == 0){
        echo "<script type='text/javascript'> alert('You are not an assistant.') </script>";
        session_destroy();
        unset($_SESSION['username']);
        echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
        exit(0);
    }
}
catch (Exception $e) {
    echo "<script type='text/javascript'> alert('Error when query if is a valid assistant.') </script>";
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
    exit(0);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Assistant</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="css/homepage.css">
</head>

<body>
    <div class="wrapper">

        <div>
            Welcome <?php echo $_SESSION['username']?> !
        </div>

        <p>
            <a href="admin.php?logout='1'" style="color: #dddd55">logout</a>
        </p>

        <div id="first">
            <p id="currentLab"></p>
            <p id="nextLab"></p>
            <p id="requestInfo"></p>

            <form action="getNextRequest.php" style="float: left">
                <button id="getNext" class="btn btn-primary">Get Next</button>
            </form>

            <form action="suspendOneRequest.php" style="float: right">
                <button id="suspend" class="btn btn-danger">Suspend</button>
            </form>

            <form action="finishOneRequest.php">
                <button id="finish" class="btn btn-success" style="margin-left: 26.5%">Finish</button>
            </form>

            <p/>

            <p id="requestSize"></p>

            <table class='table-hover' border="1" style="width: 100%; border-color: white;">
                <caption style="font-weight: bold; font-size: large; caption-side: top; color: #dd5; text-align: center">Request History</caption>
                <tr style="color: #dddd55">
                    <th>Module</th>
                    <th>State</th>
                    <th>Generated By</th>
                    <th>Created Time</th>
                    <th>Finished Time</th>
                </tr>
                <?php
                    error_reporting(E_ALL);
                    ini_set('display_errors', 1);

                    include("credentials.php");

                    try {
                        $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

                        $pdo = new PDO($dsn,$db_username,$db_password);

                        $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

                        $stmt = $pdo->prepare("SELECT * FROM Requests WHERE Handled_By = :handled_by ORDER BY Created_Time;");

                        $stmt->bindParam(':handled_by', $_SESSION['username']);

                        $stmt->execute();

                        $rows = $stmt->fetchAll();

                        foreach ($rows as $row) {
                            echo "<tr><td>" . $row['Made_In'] . "</td><td>" . $row['State'] . "</td><td>" .$row['Generated_By'] . "</td><td>" . $row['Created_Time'] . "</td><td>" . $row['Finished_Time'] . "</td></tr>";
                        }

                    } catch (Exception $exception){
                        echo "<script type='text/javascript'> alert('Error for search history query!') </script>";
                        exit(0);
                    }
                ?>
            </table>

            <table class='table-hover' border="1" style="width: 100%; border-color: white;" id="suspendedTable">
                <caption style="font-weight: bold; font-size: large; caption-side: top; color: #dd5; text-align: center">Suspended Requests</caption>
                <tr style="color: #dddd55">
                    <th>Module</th>
                    <th>Generated By</th>
                    <th>Created Time</th>
                    <th>Suspended By</th>
                    <th>Action</th>
                </tr>

                <?php
                    error_reporting(E_ALL);
                    ini_set('display_errors', 1);

                    include("credentials.php");

                    $allModules;

                    //Query modules
                    try {
                        $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

                        $pdo = new PDO($dsn,$db_username,$db_password);

                        $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

                        $stmt = $pdo->prepare("SELECT * FROM AdminEnrollment WHERE aEmail = :email;");

                        $stmt->bindParam(":email", $_SESSION['username']);

                        $stmt->execute();

                        $allModules = $stmt->fetchAll();

                    } catch (Exception $exception){
                        echo "<script type='text/javascript'> alert('Error when search modules!') </script>";
                        exit(0);
                    }

                    foreach ($allModules as $module) {
                        try {
                            $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

                            $pdo = new PDO($dsn,$db_username,$db_password);

                            $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

                            $stmt = $pdo->prepare("SELECT * FROM Requests WHERE State = 'Suspended' AND Made_In = :module ORDER BY Created_Time;");

                            $stmt->bindParam(":module", $module['mCode']);

                            $stmt->execute();

                            $rows = $stmt->fetchAll();

                            foreach ($rows as $row) {
                                echo "<tr><td>" . $row['Made_In'] . "</td><td>" .$row['Generated_By'] . "</td><td>" . $row['Created_Time'] . "</td><td>" . $row['Handled_By'] . "</td>";
                                echo "<td><a href='finishSuspendedRequest.php?id=" . $row['ID'] . "' style='color: #dddd55'>Finish</a> </td></tr>";
                                //                echo "<td><form action='finishSuspendedRequest.php?id=" . $row['ID'] . "'><input type=\"submit\" value=\"Finish\" id=\"finishSuspend\"/></form></td></tr>";
                            }

                        } catch (Exception $exception){
                            echo "<script type='text/javascript'> alert('Error when query request') </script>";
                            exit(0);
                        }
                    }
                ?>
            </table>
        </div>
    </div>

    <script>

        function initial() {
            $.get("nextRequest.php", function (email) {
                if (email === "null"){
                    document.getElementById('requestInfo').innerHTML = "There is no request in the waiting queue you can handle now.";
                    document.getElementById('getNext').disabled = true;
                    document.getElementById('finish').disabled = true;
                    document.getElementById('suspend').disabled = true;
                } else if (email === "Has request") {
                    document.getElementById('requestInfo').innerHTML = "There is one request available.";
                    document.getElementById('getNext').disabled = false;
                    document.getElementById('finish').disabled = true;
                    document.getElementById('suspend').disabled = true;
                } else {
                    document.getElementById('requestInfo').innerHTML = "You should be coming for " + email + ".";
                    document.getElementById('getNext').disabled = true;
                    document.getElementById('finish').disabled = false;
                    document.getElementById('suspend').disabled = false;
                }
            });

            $.get("requestSize.php", function (size) {
                document.getElementById('requestSize').innerHTML = 'Waiting requests size (includes being handling ones): ' + size;
            });

            $.get("currentLab.php", function (lab) {
                if (lab === 'duplicate labs') {
                    document.getElementById('currentLab').innerHTML = "There are more than 1 labs in the room, please contact admin!";
                } else if (lab === "no lab") {
                    document.getElementById('currentLab').innerHTML = "No lab now.";
                } else {
                    document.getElementById("currentLab").innerHTML = "Current lab is " + lab + ".";
                }
            });

            $.get("nextLab.php", function (lab) {
                if (lab === 'no lab after') {
                    document.getElementById("nextLab").innerHTML = "No more lab today.";
                } else {
                    document.getElementById("nextLab").innerHTML = "Next lab is " + lab + ".";
                }
            });
        }

        initial();

        setInterval(initial, 5000)


    </script>

</body>

</html>

