<?php
session_start();

if (!isset($_SESSION['username'])) {
    echo "<script type='text/javascript'> alert('Please log in first!') </script>";
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
}
if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['username']);
    echo "<meta http-equiv='Refresh' content='0;URL=adminLogin.php'>";
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Assistant</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="css/homepage.css">
</head>

<body>
    <div class="wrapper">

        <div>
            Welcome <?php echo $_SESSION['username']?> !
        </div>

        <p>
            <a href="admin.php?logout='1'" style="color: #dddd55">logout</a>
        </p>

        <div id="first">
            <p id="requestInfo"></p>

            <form action="getNextRequest.php" style="float: left">
                <button id="getNext" class="btn btn-primary">Get Next</button>
            </form>

            <form action="suspendOneRequest.php" style="float: right">
                <button id="suspend" class="btn btn-danger">Suspend</button>
            </form>

            <form action="finishOneRequest.php">
                <button id="finish" class="btn btn-success" style="margin-left: 30%">Finish</button>
            </form>

            <p/>

            <p id="requestSize"></p>

            <table class='table-hover' border="1" style="width: 100%;">
                <caption style="font-weight: bold; font-size: large; caption-side: top; color: #dd5; text-align: center">Request History</caption>
                <tr style="color: #dddd55">
                    <th>State</th>
                    <th>Generated By</th>
                    <th>Created Time</th>
                    <th>Finished Time</th>
                </tr>
                <?php
                error_reporting(E_ALL);
                ini_set('display_errors', 1);

                include("credentials.php");

                try {
                    $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

                    $pdo = new PDO($dsn,$db_username,$db_password);

                    $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

                    $stmt = $pdo->prepare("SELECT * FROM Requests WHERE Handled_By = :handled_by;");

                    $stmt->bindParam(':handled_by', $_SESSION['username']);

                    $stmt->execute();

                    $rows = $stmt->fetchAll();

                    foreach ($rows as $row) {
                        echo "<tr><td>" . $row['State'] . "</td><td>" .$row['Generated_By'] . "</td><td>" . $row['Created_Time'] . "</td><td>" . $row['Finished_Time'] . "</td></tr>";
                    }

                } catch (Exception $exception){
                    echo "<script type='text/javascript'> alert('Error for search history query!') </script>";
                    exit(0);
                }
                ?>
            </table>

            <table class='table-hover' border="1" style="width: 100%;">
                <caption style="font-weight: bold; font-size: large; caption-side: top; color: #dd5; text-align: center">Suspended Requests</caption>
                <tr style="color: #dddd55">
                    <th>State</th>
                    <th>Generated By</th>
                    <th>Created Time</th>
                    <th>Suspended By</th>
                    <th>Action</th>
                </tr>

                <?php
                error_reporting(E_ALL);
                ini_set('display_errors', 1);

                include("credentials.php");

                try {
                    $dsn = 'mysql:dbname='.$db_database.';host='.$db_host;

                    $pdo = new PDO($dsn,$db_username,$db_password);

                    $pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );

                    $stmt = $pdo->prepare("SELECT * FROM Requests WHERE State = 'Suspended';");

                    $stmt->execute();

                    $rows = $stmt->fetchAll();

                    foreach ($rows as $row) {
                        echo "<tr><td>" . $row['State'] . "</td><td>" .$row['Generated_By'] . "</td><td>" . $row['Created_Time'] . "</td><td>" . $row['Handled_By'] . "</td>";
                        echo "<td><a href='finishSuspendedRequest.php?id=" . $row['ID'] . "' style='color: #dddd55'>Finish</a> </td></tr>";
        //                echo "<td><form action='finishSuspendedRequest.php?id=" . $row['ID'] . "'><input type=\"submit\" value=\"Finish\" id=\"finishSuspend\"/></form></td></tr>";
                    }

                } catch (Exception $exception){
                    echo "<script type='text/javascript'> alert('Error for search history query!') </script>";
                    exit(0);
                }
                ?>
            </table>
        </div>
    </div>

    <script>

        function initial() {
            $.get("nextRequest.php", function (email) {
                if (email === "null"){
                    document.getElementById('requestInfo').innerHTML = "There is no waiting request with no assistant handling in the queue now.";
                    document.getElementById('getNext').disabled = true;
                    document.getElementById('finish').disabled = true;
                    document.getElementById('suspend').disabled = true;
                } else if (email.includes("??")) {
                    document.getElementById('requestInfo').innerHTML = "There is one request available.";
                    document.getElementById('getNext').disabled = false;
                    document.getElementById('finish').disabled = true;
                    document.getElementById('suspend').disabled = true;
                } else {
                    document.getElementById('requestInfo').innerHTML = "You should be coming for " + email + ".";
                    document.getElementById('getNext').disabled = true;
                    document.getElementById('finish').disabled = false;
                    document.getElementById('suspend').disabled = false;
                }
            });

            $.get("requestSize.php", function (size) {
                document.getElementById('requestSize').innerHTML = 'Waiting requests size (includes being handling ones): ' + size;
            });
        }

        initial();

        setInterval(initial, 5000)


    </script>

</body>

</html>

